sanity_check: Check for required programs at startup

diff --git a/xdcommits b/xdcommits
--- a/xdcommits
+++ b/xdcommits
@@ -182,6 +182,13 @@ sanity_check() {
 			exit 1
 		fi
 	done
+
+	for prog in mplayer convert; do
+		if [ ! -x "$(which $prog)" ]; then
+			echo "ERROR: '$prog' is required."
+			exit 1
+		fi
+	done
 }
 
 main "$@"
