Implement enable and disable commands

diff --git a/xdcommits b/xdcommits
--- a/xdcommits
+++ b/xdcommits
@@ -17,6 +17,7 @@ XDCOMMITS_ROOT=$(dirname $(readlink -f $0))
 
 main() {
 	local command=$1
+	shift
 	if [ -z "$command" ]; then
 		print_usage
 		exit 1
@@ -27,7 +28,7 @@ main() {
 			print_usage
 			;;
 		enable|capture|disable|show)
-			do_$command
+			do_$command "$@"
 			;;
 		*)
 			echo "Skąd znasz te prawdy? Nie z sztuki wróżenia!"
@@ -71,13 +72,40 @@ get_outdir() {
 }
 
 do_enable() {
-	echo "Not implemented yet"
+	local git_dir
+	if [ "$#" -gt 0 ]; then
+		if [ "$1" = "-g" ]; then
+			git_dir=/usr/share/git-core/templates
+		else
+			print_usage
+			exit 1
+		fi
+	else
+		require_repo
+		git_dir=$(git rev-parse --git-dir)
+	fi
+	enable_hook $git_dir/hooks/post-commit
 	exit 1
 }
 
+enable_hook() {
+	local hook="$1"
+
+	if [ ! -f "$hook" ]; then
+		[ -w $(dirname $hook) ] || die "Can't write to $hook"
+		echo "Writing $hook:"
+		echo -e "#!/bin/sh\nxdcommits capture" | tee $hook
+		chmod +x $hook
+	else
+		[ -w $hook ] || die "Can't write to $hook"
+		grep -q -F 'xdcommits capture' $hook && die "Already enabled on $hook"
+		echo "Enabling xdcommits on $hook"
+		sed -i '2s/^/xdcommits capture\n/' $hook
+	fi
+}
+
 do_disable() {
-	echo "Not implemented yet"
-	exit 1
+	die "I ain't no scipp editor! Do it yourself."
 }
 
 do_show() {
@@ -89,6 +117,11 @@ do_show() {
 		exit 1
 	fi
 	exec $IMAGE_VIEWER $filename
+}
+
+die() {
+	echo "$@"
+	exit 1
 }
 
 print_usage() {
