Fixed the sanity_check to support checking for either mplayer or ffmpeg

diff --git a/xdcommits b/xdcommits
--- a/xdcommits
+++ b/xdcommits
@@ -199,12 +199,16 @@ sanity_check() {
 		fi
 	done
 
-	for prog in mplayer convert; do
+	for prog in convert; do
 		if [ ! -x "$(which $prog)" ]; then
 			echo "ERROR: '$prog' is required."
 			exit 1
 		fi
 	done
+    if [ ! -x "$(which ffmpeg)" ] && [ ! -x "$(which mplayer)" ]; then
+        echo "ERROR: either mplayer or ffmpeg are required."
+        exit 1
+    fi
 }
 
 main "$@"
